# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: igoralmeida
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: dynamodb-crud-api-gateway
service: dynamodb-crud-api

provider:
    name: aws
    runtime: nodejs20.x
    stage: dev
    region: us-east-1
    environment:
        DDB_TABLE_NAME: ${self:custom.customersTableName}

custom:
    dynamodb:
        stages:
            - dev
        start:
            migrate: true

    # HTTP proxy config
    # serverless-offline:
    #     resourceRoutes: true

    apiKeys:
        - name: dynamodb-crud-api-key

    customersTableName: customers-table-${self:provider.stage}

plugins:
    - serverless-iam-roles-per-function
    - serverless-add-api-key
    - serverless-dynamodb
    - serverless-offline

functions:
    createCustomer:
        handler: api.createCustomer
        name: createCustomer
        memorySize: 128
        timeout: 5
        events:
            - http:
                  path: customer
                  method: POST
                  private: true
        iamRoleStatements:
            - Effect: "Allow"
              Action:
                  - "dynamodb:PutItem"
              Resource: !GetAtt CustomersTable.Arn

    getAllCustomers:
        handler: api.getAllCustomers
        name: getAllCustomers
        memorySize: 128
        timeout: 5
        events:
            - http:
                  path: customer
                  method: GET
                  private: true
        iamRoleStatements:
            - Effect: "Allow"
              Action:
                  - "dynamodb:Scan"
              Resource: !GetAtt CustomersTable.Arn

resources:
    Resources:
        CustomersTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.customersTableName}
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
